const LESSONS = {
  dars_1:
    "BQACAgIAAxkBAAIBL2J0bprIgmg7eW5Udk9IpbGWtSPKAAJFGgACdquhSzFKYFKK9fNjJAQ",
  dars_2:
    "BQACAgIAAxkBAAIBMWJ0bs7wXnazF_RORSG0lrgGLB7XAAJGGgACdquhS_WLT_gWyqdjJAQ",
  dars_3:
    "BQACAgIAAxkBAAIBM2J0bvXqWbsx8CAkoxEvRD9ULblHAAJHGgACdquhS80ImVZ8o3ODJAQ",
  dars_4: "BQACAgIAAxkBAAIBNWJ0byXYZrs3O784v-UAAfBdJ3INjAACSBoAAnaroUtyyHkubpg16iQE",
  dars_5: "BQACAgIAAxkBAAIBNmJ0byVtH3OFzYEyZNwzl00xJXLxAAJJGgACdquhS1MGyjOlcr0SJAQ"
}

module.exports = LESSONS
